core/urls.py
from django.urls import path

from core import views

app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('room/list/', views.room_list, name='room-list'),
    path('room/add/', views.room_add, name='room-add'),
    path('room/<int:room_id>/change/', views.room_change, name='room-change'),
    path('meeting/list/', views.meeting_list, name='meeting-list'),
    path('meeting/add/', views.meeting_add, name='meeting-add'),
    path('meeting/<int:meeting_id>/change/', views.meeting_change, name='meeting-change'),
    path('meeting/calendar/', views.meeting_calendar, name='meeting-calendar'),
]

rooms/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import routers
from rest_framework.documentation import include_docs_urls
from rest_framework.permissions import AllowAny

from api import views as api_views
from rooms import settings

router = routers.DefaultRouter()
router.register(r'rooms', api_views.RoomViewSet)
router.register(r'meetings', api_views.MeetingViewSet)


schema_view = get_schema_view(
   openapi.Info(
      title="rooms",
      default_version='v1',
      description="agendamento de salas",
      contact=openapi.Contact(email=""),
   ),
   public=True,
   permission_classes=(AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls', namespace='core')),
    path('api/', include((router.urls, 'api'), namespace='api')),
    path('docs/', include_docs_urls(title='api')),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

core/models.py
from django.core.exceptions import ValidationError
from django.db import models


class Room(models.Model):
    name = models.CharField(max_length=100, unique=True, db_index=True)
    slug = models.SlugField()
    description = models.CharField(max_length=200, blank=True, null=True)
    color = models.CharField(max_length=20, blank=True, null=True)

    date_added = models.DateTimeField(auto_now_add=True)
    date_changed = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.color = self.color.lower() if self.color else ''
        return super().save(*args, **kwargs)

    def conflict(self, date, start, end, meeting_id):
        return self.meetings.filter(
            date=date,
            start__lt=end,
            end__gt=start,
        ).exclude(
            id=meeting_id
        ).exists()


class Meeting(models.Model):
    SCHEDULED = 'scheduled'
    CANCELED = 'canceled'
    STATUS_CHOICES = (
        (SCHEDULED, 'Scheduled'),
        (CANCELED, 'Canceled'),
    )
    room = models.ForeignKey(
        'core.Room',
        related_name='meetings',
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=200, blank=True, null=True)
    status = models.CharField(
        max_length=20,
        choices=STATUS_CHOICES,
        default=SCHEDULED,
        db_index=True
    )
    date = models.DateField(db_index=True)
    start = models.TimeField(db_index=True)
    end = models.TimeField()

    date_added = models.DateTimeField(auto_now_add=True)
    date_changed = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def clean(self):
        if self.start and self.end:
            if self.start > self.end:
                raise ValidationError('Start cannot be greater than end.')
            if self.room.conflict(
                date=self.date,
                start=self.start,
                end=self.end,
                meeting_id=self.id
            ) and self.status == self.SCHEDULED:
                raise ValidationError(
                    'Room {room} already booked in this period.'.format(
                        room=self.room.name
                    )
                )

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

core/forms.py
from django import forms

from core.models import Meeting, Room


class RoomChangeForm(forms.ModelForm):
    class Meta:
        model = Room
        fields = (
            'name',
            'description',
            'color',
        )


class MeetingChangeForm(forms.ModelForm):
    date = forms.DateField(input_formats=['%d/%m/%Y'])

    class Meta:
        model = Meeting
        fields = (
            'room',
            'name',
            'description',
            'status',
            'date',
            'start',
            'end',
        )

core/views.py
from django.contrib import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.text import slugify

from core.forms import MeetingChangeForm, RoomChangeForm
from core.models import Meeting, Room


def index(request):
    return render(request, 'core/index.html')


def room_list(request):
    rooms = Room.objects.order_by('name')
    return render(request, 'core/room_list.html', {
        'rooms': rooms,
    })


def meeting_list(request):
    meetings = Meeting.objects.prefetch_related(
        'room',
    ).order_by('date', 'start')
    return render(request, 'core/meeting_list.html', {
        'meetings': meetings,
    })


def meeting_calendar(request):
    meetings = Meeting.objects.prefetch_related(
        'room',
    ).order_by('date', 'start')
    return render(request, 'core/meeting_calendar.html', {
        'meetings': meetings,
    })


def room_add(request):
    form = RoomChangeForm()
    if request.method == 'POST':
        form = RoomChangeForm(request.POST)
        if form.is_valid():
            room = form.save(commit=False)
            room.slug = slugify(room.name)
            room.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                extra_tags='success',
                message='Sala {name} criada com sucesso.'.format(
                    name=room.name
                )
            )
            return redirect('core:room-list')
    return render(request, 'core/room_change.html', {
        'form': form,
    })


def room_change(request, room_id):
    room = get_object_or_404(Room, id=room_id)
    form = RoomChangeForm(instance=room)
    if request.method == 'POST':
        form = RoomChangeForm(data=request.POST, instance=room)
        if form.is_valid():
            room = form.save(commit=False)
            room.slug = slugify(room.name)
            room.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                extra_tags='success',
                message='Sala {name} editada com sucesso.'.format(
                    name=room.name
                )
            )
            return redirect('core:room-list')
    return render(request, 'core/room_change.html', {
        'form': form,
        'room': room,
    })


def meeting_add(request):
    rooms = Room.objects.all()
    form = MeetingChangeForm()
    if request.method == 'POST':
        form = MeetingChangeForm(request.POST)
        if form.is_valid():
            meeting = form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                extra_tags='success',
                message='Reunião {name} criada com sucesso.'.format(
                    name=meeting.name
                )
            )
            return redirect('core:meeting-list')
    return render(request, 'core/meeting_change.html', {
        'form': form,
        'rooms': rooms,
    })


def meeting_change(request, meeting_id):
    meeting = get_object_or_404(Meeting, id=meeting_id)
    rooms = Room.objects.all()
    form = MeetingChangeForm(instance=meeting)
    if request.method == 'POST':
        form = MeetingChangeForm(data=request.POST, instance=meeting)
        if form.is_valid():
            meeting.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                extra_tags='success',
                message='Reunião {name} editada com sucesso.'.format(
                    name=meeting.name
                )
            )
            return redirect('core:meeting-list')
    return render(request, 'core/meeting_change.html', {
        'form': form,
        'rooms': rooms,
        'meeting': meeting,
    })

core/templates/core/base.html
{% load static %}
<!doctype html>
<html>
<head>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-147225311-4"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-147225311-4');
    </script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="google-site-verification" content="83fcqoPn-YTkXathQiicW-x3U2RWZh4PaPUzk91wtjY" />
    <script src="{% static 'core/js/jquery-3.3.1.slim.min.js' %}"></script>

    <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {% block extra_header %}
    {% endblock %}

    <title>rooms</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-link">
                        <a class="text-dark" href="{% url 'core:index' %}"><strong>home</strong></a>
                    </li>
                    <li class="nav-link">
                        <a class="text-dark" href="{% url 'core:meeting-calendar' %}"><strong>calendário</strong></a>
                    </li>
                </ul>
                <div class="dropdown ml-auto mt-2 mt-lg-0">
                    <a class="dropdown-toggle nav-link" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="cursor: pointer;">
                        <strong>salas</strong>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'core:room-list' %}">listar</a>
                        <a class="dropdown-item" href="{% url 'core:room-add' %}">incluir</a>
                    </div>
                </div>
                <div class="dropdown mt-2 mt-lg-0">
                    <a class="dropdown-toggle nav-link" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="cursor: pointer;">
                        <strong>reuniões</strong>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="{% url 'core:meeting-list' %}">listar</a>
                        <a class="dropdown-item" href="{% url 'core:meeting-add' %}">incluir</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

    <footer class="footer border-top">
        <div class="text-center mt-3">desenvolvido por:
            <a href=""> Elias e Jean</a>
        </div>
    </footer>
    <script src="{% static 'core/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'core/js/popper.min.js' %}"></script>
</body>
</html>

core/templates/core/basic_template.html
{% extends 'core/base.html' %}
{% block content %}
    <div class="container text-center py-5 my-5">
        <h1 class="display-4">{% block h1 %}{% endblock %}</h1>
        <p class="lead mt-3">
            {% block lead %}{% endblock %}
        </p>
    {% block api_url %}
    {% endblock %}
    </div>
    <div class="container text-center">
        {% block main_content %}{% endblock %}
    </div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}


{% block content %}
    <div class="container text-center py-5 my-5">
        <h1 class="display-2">rooms</h1>
        <p class="lead mt-3">
            agendamento de salas
        </p>
    </div>
{% endblock %}

core/templates/core/meeting_calendar.html
{% extends 'core/basic_template.html' %}
{% load static %}
{% block extra_header %}
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.6.0/fullcalendar.css' />
    <script src='http://code.jquery.com/jquery-1.11.3.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.1/moment.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/2.6.0/fullcalendar.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.js'></script>
    <script src={% static 'core/js/pt-br.js' %}></script>
{% endblock %}
{% block h1 %}
    calendário de reuniões
{% endblock %}
{% block lead %}
    veja as reuniões agendadas
{% endblock %}
{% block main_content %}
    <div class="container text-center">
        <div id='calendar'></div>
    </div>
    <script>
        $(document).ready(function() {
            $('#calendar').fullCalendar({
                locale: 'pt-br',
                header: {
                    left: 'prev,next today',
                    center: 'title',
                    right: 'month,agendaWeek,agendaDay',
                },
                events: [
                {% for meeting in meetings %}
                    {
                        title  : '{{ meeting.name }}',
                        start  : '{{ meeting.date|date:'Y-m-d' }}T{{ meeting.start|date:'H:i' }}',
                        end  : '{{ meeting.date|date:'Y-m-d' }}T{{ meeting.end|date:'H:i' }}',
                        color: '{{ meeting.room.color|default:'darkblue' }}',
                        url: '{% url 'api:meeting-list' %}{{ meeting.id }}',
                        allDay : false,
                        {% if meeting.status == 'canceled' %}
                            borderColor: 'red',
                            textColor: 'darkred',
                        {% else %}
                            borderColor: 'black',
                        {% endif %}
                    },
                {% endfor %}
              ]
            })
        });
    </script>
{% endblock %}

core/templates/core/meeting_change.html
{% extends 'core/basic_template.html' %}
{% load core_tags %}
{% load i18n %}
{% block h1 %}
    {% if not meeting %}
        inclua novas reuniões
    {% else %}
        edite esta reunião
    {% endif %}
{% endblock %}
{% block api_url %}
    {% if meeting %}
        <a href="{% url 'api:meeting-detail' meeting.id %}">API</a>
    {% endif %}
{% endblock %}
{% block main_content %}
    {% language 'pt-BR' %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{ error }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
    <form method="post">
        {% csrf_token %}
        <div class="form-group row">
            <label for="{{ form.room.id_for_label }}" class="col-sm-2 col-form-label">{{ form.room.label|translation }}</label>
            <div class="col-sm-10">
                <select name="{{ form.room.name }}" id="{{ form.room.id_for_label }}" class="form-control m-input" required>
                    {% if meeting %}
                        {% for room in rooms %}
                            <option value="{{ room.id }}"
                                {% if room.id == meeting.room.id %}
                                    selected
                                {% endif %}
                                >{{ room.name }}
                            </option>
                        {% endfor %}
                    {% else %}
                        {% for choice in form.room.field.choices %}
                            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                        {% endfor %}
                    {% endif %}
                </select>
                {% for error in form.room.errors %}
                    <small class="form-text text-danger">{{ error }}</small>
                {% endfor %}
            </div>
        </div>
        <div class="form-group row">
            <label for="{{ form.name.id_for_label }}" class="col-sm-2 col-form-label">{{ form.name.label|translation }}</label>
            <div class="col-sm-10">
                <input type="{{ form.name.field.widget.input_type }}" class="form-control" id="{{ form.name.id_for_label }}" name="{{ form.name.name }}" value="{{ form.name.value|default:'' }}" required>
                {% for error in form.name.errors %}
                    <small class="form-text text-danger">{{ error }}</small>
                {% endfor %}
            </div>
        </div>
        <div class="form-group row">
            <label for="{{ form.description.id_for_label }}" class="col-sm-2 col-form-label">{{ form.description.label|translation }}</label>
            <div class="col-sm-10">
                <input type="{{ form.description.field.widget.input_type }}" class="form-control" id="{{ form.description.id_for_label }}" name="{{ form.description.name }}" value="{{ form.description.value|default:'' }}">
                {% for error in form.description.errors %}
                    <small class="form-text text-danger">{{ error }}</small>
                {% endfor %}
            </div>
        </div>
        <div class="form-group row">
            <label for="{{ form.status.id_for_label }}" class="col-sm-2 col-form-label">{{ form.status.label|translation }}</label>
            <div class="col-sm-10">
                <select name="{{ form.status.name }}" id="{{ form.status.id_for_label }}" class="form-control m-input" required>
                    {% for choice in form.status.field.choices %}
                        <option value="{{ choice.0 }}">{{ choice.1|translation }}</option>
                    {% endfor %}
                </select>
                {% for error in form.status.errors %}
                    <small class="form-text text-danger">{{ error }}</small>
                {% endfor %}
            </div>
        </div>
        <div class="form-group row">
            <label for="{{ form.date.id_for_label }}" class="col-sm-2 col-form-label">{{ form.date.label|translation }}</label>
            <div class="col-sm-10">
                <input type="{{ form.date.field.widget.input_type }}" class="form-control" id="{{ form.date.id_for_label }}" name="{{ form.date.name }}" placeholder="dd/mm/aaaa" required
                {% if not meeting %}
                    value="{{ form.date.value|default:'' }}">
                {% else %}
                    value="{{ meeting.date|date:'d/m/Y' }}">
                {% endif %}
                {% for error in form.date.errors %}
                    <small class="form-text text-danger">{{ error }}</small>
                {% endfor %}
            </div>
        </div>
        <div class="form-group row">
            <label for="{{ form.start.id_for_label }}" class="col-sm-2 col-form-label">{{ form.start.label|translation }}</label>
            <div class="col-sm-10">
                <input type="{{ form.start.field.widget.input_type }}" class="form-control" id="{{ form.start.id_for_label }}" name="{{ form.start.name }}" value="{{ form.start.value|default:'' }}" placeholder="hh:mm" required>
                    {% for error in form.start.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
            </div>
        </div>
        <div class="form-group row">
            <label for="{{ form.end.id_for_label }}" class="col-sm-2 col-form-label">{{ form.end.label|translation }}</label>
            <div class="col-sm-10">
                <input type="{{ form.end.field.widget.input_type }}" class="form-control" id="{{ form.end.id_for_label }}" name="{{ form.end.name }}" value="{{ form.end.value|default:'' }}" placeholder="hh:mm" required>
                {% for error in form.end.errors %}
                    <small class="form-text text-danger">{{ error }}</small>
                {% endfor %}
            </div>
        </div>
        <div class="form-group row">
            <div class="col">
                <button type="submit" class="btn btn-primary">salvar</button>
            </div>
        </div>
    </form>
    {% endlanguage %}
    {% block extra_header %}
        <script src="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/js/gijgo.min.js" type="text/javascript"></script>
        <link href="https://cdn.jsdelivr.net/npm/gijgo@1.9.10/css/gijgo.min.css" rel="stylesheet" type="text/css" />
    {% endblock %}
    <script>
        $('#{{ form.date.id_for_label }}').datepicker({
            uiLibrary: 'bootstrap4',
            format: 'dd/mm/yyyy',
        });
        $('#{{ form.start.id_for_label }}').timepicker({
            format: 'HH:MM',
            mode: '24hr',
        });
        $('#{{ form.end.id_for_label }}').timepicker({
            format: 'HH:MM',
            mode: '24hr',
        });
    </script>
{% endblock %}

core/templates/core/meeting_list.html
{% extends 'core/base.html' %}
{% load core_tags %}
{% block content %}
    <div class="container text-center py-5 my-5">
        <h1 class="display-4">lista de reuniões</h1>
        <p class="lead mt-3">
            veja as reuniões agendadas
        </p>
        <a href="{% url 'api:meeting-list' %}" class="">API</a>
    </div>
    <div class="container text-center">
    {% if messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {% for message in messages %}
                {{ message }}<br>
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
        {% if meetings %}
            <table id="meetingTable" class="table table-sm table-hover">
                <thead>
                    <tr>
                        <th scope="col">nome</th>
                        <th scope="col">sala</th>
                        <th scope="col">status</th>
                        <th scope="col">data</th>
                        <th scope="col">início</th>
                        <th scope="col">fim</th>
                        <th scope="col">editar</th>
                    </tr>
                </thead>
                <tbody>
                    {% for meeting in meetings %}
                        <tr>
                            <td>{{ meeting.name|default:'' }}</td>
                            <td>{{ meeting.room.name|default:'' }}</td>
                            {% if meeting.status == 'scheduled' %}
                                <td>agendada</td>
                            {% else %}
                                <td style="color: red;">cancelada</td>
                            {% endif %}
                            <td>{{ meeting.date|date:'d/m/Y'|default:'' }}</td>
                            <td>{{ meeting.start|date:'H:i'|default:'' }}</td>
                            <td>{{ meeting.end|date:'H:i'|default:'' }}</td>
                            <td><a href="{% url 'core:meeting-change' meeting.id %}"><i class="material-icons text-dark">&#xe22b;</i></a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="alert alert-danger" role="alert">
                <strong>Oops!</strong> Nenhuma <a class="alert-link">reunião</a> agendada.
            </div>
        {% endif %}
    </div>
    <script>
        $(document).ready( function () {
            $('#meetingTable').DataTable();
        } );
    </script>
    <script>
        $("#meetingTable").dataTable({
            "bJQueryUI": true,
            "oLanguage": {
                "sProcessing":   "Processando...",
                "sLengthMenu":   "Mostrar _MENU_ registros",
                "sZeroRecords":  "Não foram encontrados resultados",
                "sInfo":         "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "sInfoEmpty":    "Mostrando de 0 até 0 de 0 registros",
                "sInfoFiltered": "",
                "sInfoPostFix":  "",
                "sSearch":       "Buscar:",
                "sUrl":          "",
                "oPaginate": {
                    "sFirst":    "Primeiro",
                    "sPrevious": "Anterior",
                    "sNext":     "Seguinte",
                    "sLast":     "Último"
                }
            }
        })
    </script>
{% endblock %}

core/templates/core/room_change.html
{% extends 'core/basic_template.html' %}
{% load core_tags %}
{% load i18n %}
{% block h1 %}
    {% if not room %}
        inclua novas salas
    {% else %}
        edite esta sala
    {% endif %}
{% endblock %}
{% block api_url %}
    {% if room %}
        <a href="{% url 'api:room-detail' room.id %}" target="_blank">API</a>
    {% endif %}
{% endblock %}
{% block main_content %}
    <form method="post">
        {% csrf_token %}
        <div class="form-group row">
            <label for="{{ form.name.id_for_label }}" class="col-sm-2 col-form-label">{{ form.name.label|translation }}</label>
            <div class="col-sm-10">
                <input type="{{ form.name.field.widget.input_type }}" class="form-control" id="{{ form.name.id_for_label }}" name="{{ form.name.name }}" value="{{ form.name.value|default:'' }}" required>
                {% language 'pt-BR' %}
                    {% for error in form.name.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                {% endlanguage %}
            </div>
        </div>
        <div class="form-group row">
            <label for="{{ form.description.id_for_label }}" class="col-sm-2 col-form-label">{{ form.description.label|translation }}</label>
            <div class="col-sm-10">
                <input type="{{ form.description.field.widget.input_type }}" class="form-control" id="{{ form.description.id_for_label }}" name="{{ form.description.name }}" value="{{ form.description.value|default:'' }}">
                {% language 'pt-BR' %}
                    {% for error in form.description.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                {% endlanguage %}
            </div>
        </div>
        <div class="form-group row">
            <label for="{{ form.color.id_for_label }}" class="col-sm-2 col-form-label">{{ form.color.label|translation }}</label>
            <div class="col-sm-10">
                <input type="{{ form.color.field.widget.input_type }}" class="form-control mr-auto" id="{{ form.color.id_for_label }}" name="{{ form.color.name }}" value="{{ form.color.value|default:'' }}" required>
                <small class="form-text text-info">digite a cor em inglês para aparecer corretamente no calendário.</small>
                {% language 'pt-BR' %}
                    {% for error in form.color.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                {% endlanguage %}
            </div>
        </div>
        <div class="form-group row">
            <label for="{{ form.active.id_for_label }}" class="col-sm-2 col-form-label">{{ form.active.label|translation }}</label>
            <div class="col-sm-10">
                {{ form.active }}
                {% language 'pt-BR' %}
                    {% for error in form.active.errors %}
                        <small class="form-text text-danger">{{ error }}</small>
                    {% endfor %}
                {% endlanguage %}
            </div>
        </div>
        <div class="form-group row">
            <div class="col">
                <button type="submit" class="btn btn-primary">salvar</button>
            </div>
        </div>
    </form>
{% endblock %}

core/templates/core/room_list.html
{% extends 'core/basic_template.html' %}
{% load core_tags %}

{% block h1 %}
    lista de salas
{% endblock %}
{% block lead %}
    veja aqui as salas disponíveis
{% endblock %}
{% block api_url %}
    <a href="{% url 'api:room-list' %}" target="_blank">API</a>
{% endblock %}

{% block main_content %}
    {% if messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {% for message in messages %}
                {{ message }}<br>
            {% endfor %}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
{% if rooms %}
    <table class="table table-sm table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">nome</th>
                <th scope="col">cor</th>
                <th scope="col">editar</th>
            </tr>
        </thead>
        <tbody>
            {% for room in rooms %}
                <tr>
                    <th scope="row">{{ room.id|default:'' }}</th>
                    <td>{{ room.name|default:'' }}</td>
                    <td style="color: {{ room.color }};">{{ room.color|default:'' }}</td>
                    <td><a href="{% url 'core:room-change' room.id %}"><i class="material-icons text-dark">&#xe22b;</i></a></td>
                </tr>
            {% endfor %}
        <strong></strong>
        </tbody>
    </table>
{% else %}
    <div class="alert alert-danger" role="alert">
        <strong>Oops!</strong> Nenhuma <a class="alert-link">sala</a> cadastrada.
    </div>
{% endif %}
{% endblock %}